module.exports = function(Message) {
  Message.greet = function(msg, cb) {
    process.nextTick(function() {
      msg = msg || 'hello';
      cb(null, 'Sender says ' + msg + ' to receiver');
    });
  };

  // Create a custom api that is not generated by  loopback
  // what does this  do ?? -- Based on the time it gives out greetings// Create a custom api that is not generated by  loopback
  // what does this  do ?? -- Based on the time it gives out greetingss

  Message.customGreet = function(cb){
    const currDate=new Date();
    const currhours=currDate.getHours();
    var msg="Good";
    if(currhours < 12){
      msg=msg+'Morning'
    }else if(currhours <18){
      msg=msg+'Afternoon'
    }else{s
      msg=msg+'Nights'
    }

    cb(null,msg); // cb is a standard way of defining a callback function.
  }

  Message.remoteMethod('customGreet',{
    http:{path:"/customGreet",verb:'get'},// path defines the custom path name via which you want to access this api and the verb defines the http protocol.
    returns:{arg:"greet",type:'string'} // arg is the JSON key and the type defines the datatype of the value.
  });
};
